// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoultryFarmManager.Infrastructure;

#nullable disable

namespace PoultryFarmManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DailyFeedingTimes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FeedingTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("FemaleCount")
                        .HasColumnType("integer");

                    b.Property<int>("InitialPopulation")
                        .HasColumnType("integer");

                    b.Property<int>("MaleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Shed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("UnsexedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeedingTableId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.MortalityRegistrationBatchActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumberOfDeaths")
                        .HasColumnType("integer");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("MortalityRegistrationActivities", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.ProductConsumptionBatchActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductConsumptionActivities", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.StatusSwitchBatchActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("NewStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("StatusSwitchActivities", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.WeightMeasurementBatchActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("WeightMeasurementActivities", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.FeedingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FeedingTables", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.FeedingTableDayEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPerBird")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ExpectedBirdWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte?>("ExpectedBirdWeightUnitOfMeasure")
                        .HasColumnType("smallint");

                    b.Property<Guid>("FeedingTableId")
                        .HasColumnType("uuid");

                    b.Property<byte>("FoodType")
                        .HasColumnType("smallint");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FeedingTableId");

                    b.HasIndex("FeedingTableId", "DayNumber")
                        .IsUnique();

                    b.ToTable("FeedingTableDayEntries", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Finance.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SaleOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Date");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("SaleOrderId");

                    b.HasIndex("Type");

                    b.HasIndex("VendorId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Finance.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.AssetState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Status");

                    b.ToTable("AssetStates", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Manufacturer", "UnitOfMeasure")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.SaleOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.ToTable("SaleOrders", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.SaleOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SaleOrderId")
                        .HasColumnType("uuid");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("SaleOrderItems", (string)null);
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Batch", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.FeedingTable", "FeedingTable")
                        .WithMany()
                        .HasForeignKey("FeedingTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeedingTable");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.MortalityRegistrationBatchActivity", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.ProductConsumptionBatchActivity", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoultryFarmManager.Core.Models.Inventory.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.StatusSwitchBatchActivity", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.BatchActivities.WeightMeasurementBatchActivity", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.FeedingTableDayEntry", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.FeedingTable", "FeedingTable")
                        .WithMany("DayEntries")
                        .HasForeignKey("FeedingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedingTable");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Finance.Transaction", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Inventory.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoultryFarmManager.Core.Models.Finance.Person", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoultryFarmManager.Core.Models.Inventory.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoultryFarmManager.Core.Models.SaleOrder", "SaleOrder")
                        .WithMany("Payments")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoultryFarmManager.Core.Models.Finance.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Batch");

                    b.Navigation("Customer");

                    b.Navigation("ProductVariant");

                    b.Navigation("SaleOrder");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Finance.Vendor", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Finance.Person", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactPerson");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.AssetState", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Inventory.Asset", "Asset")
                        .WithMany("States")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.ProductVariant", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Inventory.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.SaleOrder", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoultryFarmManager.Core.Models.Finance.Person", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.SaleOrderItem", b =>
                {
                    b.HasOne("PoultryFarmManager.Core.Models.SaleOrder", "SaleOrder")
                        .WithMany("Items")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.FeedingTable", b =>
                {
                    b.Navigation("DayEntries");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.Asset", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.Inventory.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("PoultryFarmManager.Core.Models.SaleOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
