name: CI

on:
    push:
        branches: ["*"]
    pull_request:
        branches:
            - "feature/**"
            - "dev"
            - "staging"
            - "main"
    workflow_dispatch:

jobs:
    frontend-build:
        uses: ./.github/workflows/reusable-frontend-build.yaml
        with:
            node_version: "22"
            run_tests: false

    backend-build-test:
        uses: ./.github/workflows/reusable-backend-build-test.yaml
        with:
            dotnet_version: "8.0.x"
            run_tests: true
            configuration: "Release"
